# Site settings
title: Anoop Toffy
description: 'I am a masters student and a research assistant at IIIT Bangalore. I blog about Machine Learning, Deep Learning and AI.'
url: 'http://www.anooptoffy.com'
baseurl: ''
google_analytics: 'UA-60971328-2'
disqus_shortname: 'anooptoffy'

author:
  name: 'Anoop Toffy'
  email: anoop.toffy90@gmail.com
  twitter_username: toffymon
  facebook_username: anoop.toffy
  github_username:  anooptoffy
  linkedin_username:  anooptoffy

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:month/:day/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false


plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
